version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./itr_service:/app/itr_service
      - ./requirements.txt:/app/requirements.txt

  db:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: <your_database_name>
    ports:
      - "5432:5432"
